services:
  vm_postgres:
    image: pgvector/pgvector:pg16
    container_name: VM_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: version_manager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - version_manager_prod_data:/var/lib/postgresql/data
    networks:
      - version_manager_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.6
    container_name: VM_redis
    env_file:
      - .env
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    volumes:
      - version_manager_redis_data:/data
    networks:
      - version_manager_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_REPLICATION_MODE=master

  serverpod:
    build:
      context: ./version_manager_server
      dockerfile: Dockerfile
    container_name: VM_server
    environment:
      - runmode=development
      - serverid=default
      - logging=normal
      - role=monolith
      - SERVERPOD_PASSWORDS_DATABASE=${POSTGRES_PASSWORD}
    command: dart bin/main.dart --mode development --apply-migrations
    env_file:
      - .env
    ports:
      - "127.0.0.1:9080:8080"
      - "127.0.0.1:9081:8081"
      - "127.0.0.1:9082:8082"
    depends_on:
      vm_postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - version_manager_network
    restart: always
    volumes:
      - ./version_manager_server/config:/app/config:ro
      - ./version_manager_server/migrations:/app/migrations:ro

  flutter_web:
    build:
      context: .
      dockerfile: ./version_manager_flutter/Dockerfile
    container_name: VM_web
    ports:
      - "127.0.0.1:9083:80"
    networks:
      - version_manager_network
    restart: unless-stopped

networks:
  version_manager_network:
    driver: bridge

volumes:
  version_manager_prod_data:
  version_manager_redis_data:
