services:
  serverpod:
    build:
      context: ./version_manager_server
      dockerfile: Dockerfile
    container_name: VM_server
    environment:
      - runmode=production
      - serverid=default
      - logging=normal
      - role=monolith
      - SERVERPOD_PASSWORD_database=${POSTGRES_PASSWORD}
      - SERVERPOD_PASSWORD_redis=${REDIS_PASSWORD}
    ports:
      - "9080:8080"
      - "9081:8081"
      - "9082:8082"
    restart: always

  flutter_web:
    build:
      context: .
      dockerfile: ./version_manager_flutter/Dockerfile
    container_name: VM_web
    ports:
      - "9083:80"
    restart: unless-stopped
