FROM ghcr.io/cirruslabs/flutter:stable AS build

WORKDIR /app
COPY . .

WORKDIR /app/version_manager_flutter

RUN flutter pub get
RUN cp lib/env.dev.json lib/.env.json
RUN flutter build web --release \
    --dart-define-from-file="lib/.env.json"

FROM nginx:alpine
COPY --from=build /app/version_manager_flutter/build/web /usr/share/nginx/html
COPY version_manager_flutter/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
