# Production configuration for manager.progger.pro

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: manager.progger.pro
  publicPort: 443
  publicScheme: https

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: manager.progger.pro
  publicPort: 443
  publicScheme: https

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: manager.progger.pro
  publicPort: 443
  publicScheme: https

# Database configuration (Docker container)
database:
  host: postgres
  port: 5432
  name: version_manager
  user: postgres
  requireSsl: false
  #isUnixSocket: false
  #maxConnectionCount: 10

# Redis configuration (Docker container)
redis:
  enabled: true
  host: redis
  port: 6379
  #user: # defaults to empty
  requireSsl: false

maxRequestSize: 524288

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: json

# futureCallExecutionEnabled: true

#futureCall:
#  concurrencyLimit: 1
#  scanInterval: 5000
